
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YumYum' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YumYum
  pod 'Alamofire', '~> 5.2'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'  
  pod 'GoogleSignIn'
  pod 'lottie-ios'
	
  target 'YumYumTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YumYumUITests' do
    # Pods for testing
  end

end
