# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YumYumy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!  
  project 'YumYumy.xcodeproj'
  # Pods for YumYumy
  pod 'Alamofire', '~> 5.2'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'  
  pod 'GoogleSignIn'
  pod 'GeoFire/Utils'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift', '~> 7.0-beta'
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'
  pod 'lottie-ios'
  pod 'NVActivityIndicatorView'
  pod 'SnapKit', '~> 5.0.0'
  pod 'KakaoSDKLink'  # 메시지(카카오링크)
  pod 'KakaoSDKTemplate'  # 메시지 템플릿 
	
  target 'YumYumyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YumYumyUITests' do
    # Pods for testing
  end

end
